### PR TITLE
Added not playing with bots as rule

### PR DESCRIPTION
**Pull request by mvarendorff**
Dunno if I overdone it. Mood is perfect for too long rules and enforcing them. But it was missing, so I added it.

### CODE REVIEW

**Review by mangstadt — CHANGES_REQUESTED** [review]
I think it should go above the "This is still SO" rule.

Suggested re-wording:

> **No playing with the bots:** You are free to use them to post the occasional cat picture or play a sneaky troll on a friend. But please don't use them to the point where the chat is purely revolving around you and others fooling around with them. You are welcome to play with them in the [Sandbox](https://chat.stackoverflow.com/rooms/1/sandbox) where many of the bots in the Java room are also present. Ignoring this rule will first lead to your messages being removed from the chat, then to a verbal warning, and eventually to a kick.

**Comment by mvarendorff** [comment]
Thanks for the inputs! I changed the text and position accordingly.

**Review by mangstadt — CHANGES_REQUESTED** [review]
Thanks @geis! One more thing: "No playing with bots" is repeated twice... xD

Also, "Sandbox" isn't linked anymore.

**Comment by mvarendorff** [comment]
^  Oops

**Comment by mangstadt** [comment]
Dang it @geis! Stop making oopsies!

**Pull request merged**
